const DEV_TEST_DATA_ROOT_FOLDER_NAME = 'UI_TEST_DATA';
const DEV_TEST_DATA_CLIENT_CODE_PREFIX = 'UI_TEST_';
const DEV_TEST_DATA_FRESH_CLIENT_FOLDER_NAME = 'Fresh Client';
const DEV_TEST_DATA_FRESH_CLIENT_CODE = 'UI_TEST_FC';
const DEV_TEST_DATA_FRESH_CLIENT_NAME = 'UI Test Fresh Client';
const DEV_TEST_DATA_CONFIGURED_CLIENT_FOLDER_NAME = 'Configured Client';
const DEV_TEST_DATA_CONFIGURED_CLIENT_CODE = 'UI_TEST_CC';
const DEV_TEST_DATA_CONFIGURED_CLIENT_NAME = 'UI Test Configured Client';
const DEV_TEST_DATA_EARLY_CLIENT_FOLDER_NAME = 'Early Client';
const DEV_TEST_DATA_EARLY_CLIENT_CODE = 'UI_TEST_EC';
const DEV_TEST_DATA_EARLY_CLIENT_NAME = 'UI Test Early Client';

type DevTestDataPurgeTarget = {
  folderName: string;
  clientCodePrefix: string;
};

const UI_DEV_TEST_DATA_PURGE_TARGET: DevTestDataPurgeTarget = {
  folderName: DEV_TEST_DATA_ROOT_FOLDER_NAME,
  clientCodePrefix: DEV_TEST_DATA_CLIENT_CODE_PREFIX,
};

export {
  DEV_TEST_DATA_ROOT_FOLDER_NAME,
  DEV_TEST_DATA_CLIENT_CODE_PREFIX,
  DEV_TEST_DATA_FRESH_CLIENT_FOLDER_NAME,
  DEV_TEST_DATA_FRESH_CLIENT_CODE,
  DEV_TEST_DATA_FRESH_CLIENT_NAME,
  DEV_TEST_DATA_CONFIGURED_CLIENT_FOLDER_NAME,
  DEV_TEST_DATA_CONFIGURED_CLIENT_CODE,
  DEV_TEST_DATA_CONFIGURED_CLIENT_NAME,
  DEV_TEST_DATA_EARLY_CLIENT_FOLDER_NAME,
  DEV_TEST_DATA_EARLY_CLIENT_CODE,
  DEV_TEST_DATA_EARLY_CLIENT_NAME,
  UI_DEV_TEST_DATA_PURGE_TARGET,
};
export type { DevTestDataPurgeTarget };
